/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bil481;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void testFound() {
        ArrayList<Integer> list = new ArrayList<Integer>();
        list.add(1);
        list.add(2);
        list.add(3);
        list.add(4);
        list.add(5);
        assertTrue(App.search(list, 3));
    }

    @Test
    public void testNotFound() {
        ArrayList<Integer> list = new ArrayList<Integer>();
        list.add(1);
        list.add(2);
        list.add(3);
        list.add(4);
        list.add(5);
        assertFalse(App.search(list, 6));
    }

    @Test
    public void testEmptyList() {
        ArrayList<Integer> list = new ArrayList<Integer>();
        assertFalse(App.search(list, 6));
    }

    @Test
    public void testNullList() {
        assertFalse(App.search(null, 6));
    }
}
