/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bil481;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static boolean search(ArrayList<Integer> list, int key) {
        if (list == null || list.size() == 0)
            return false;

        for (int i = 0; i < list.size(); i++) {
            if (list.get(i) == key) {
                return true;
            }
        }

        return false;
    }
}
