/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bil481;

import java.util.ArrayList;
// import static spark.Spark.get;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        /*
        get("/compute",
            (req, res) -> {
                Map<String, String> map = new HashMap<String, String>();
                map.put("result", "not computed yet.");
                return new ModelAndView(map, "compute.mustache");
            },
            new MustacheTemplateEngine()
        );
        */
    }

    public static boolean search(ArrayList<Integer> list, int key) {
        if (list == null || list.size() == 0)
            return false;

        for (int i = 0; i < list.size(); i++) {
            if (list.get(i) == key) {
                return true;
            }
        }

        return false;
    }
}
